/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_suning_jnimode_jnibase_JniUtils */

#ifndef _Included_com_android_suning_jnimode_jnibase_JniUtils
#define _Included_com_android_suning_jnimode_jnibase_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_suning_jnimode_jnibase_JniUtils
 * Method:    encryptionString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_suning_jnimode_jnibase_JniUtils_encryptionString
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_android_suning_jnimode_jnibase_JniUtils
 * Method:    decryptionString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_suning_jnimode_jnibase_JniUtils_decryptionString
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
